version: '3.4'

services:
  web:
    image: ${APP_IMAGE}
    environment:
      DEBUG: "${DEBUG}"
      PYTHONUNBUFFERED: "${PYTHONUNBUFFERED}"
      DB_ENGINE: "${DB_ENGINE}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
      AD_DNS_NAME: "${AD_DNS_NAME}"
      AD_LDAP_PORT: "${AD_LDAP_PORT}"
      LDAP_AUTH_USE_TLS: "${LDAP_AUTH_USE_TLS}"
      LDAP_AUTH_SEARCH_BASE: "${LDAP_AUTH_SEARCH_BASE}"
      LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN: "${LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN}"
      CRON_TOKEN: "${CRON_TOKEN}"
      EMAIL_BACKEND: "${EMAIL_BACKEND}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      EMAIL_FROM: "${EMAIL_FROM}"
      EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
      CONTRACT_EXPIRATION_NOTIFICATIONS_EMAIL: "${CONTRACT_EXPIRATION_NOTIFICATIONS_EMAIL}"
    deploy:
      labels:
        - "traefik.frontend.rule=Host:${APP_HOST}"
        - "traefik.port=8000"
        - "traefik.enable=true"
        - "traefik.tags=traefik-public"
        - "traefik.docker.network=traefik-public"
        - "traefik.webservice.frontend.entryPoints=http"
      restart_policy:
        condition: on-failure
    volumes:
      - media:/usr/src/app/media
    networks:
      - default
      - traefik-public
  cron:
    image: cethy/alpine-supercronic
    environment:
      CRON_TOKEN: "${CRON_TOKEN}"
    entrypoint: /bin/sh
    command: "-c \" echo \'30 8 1,15 * 5 wget -O - web:8000/cron/?token=$${CRON_TOKEN} 2>&1\' > /etc/crontab & supercronic /etc/crontab \" "
    networks:
      - default

volumes:
  media:
    driver: nfs
    driver_opts:
      share: "${MEDIA_VOLUME_SHARE}"

networks:
  default:
  traefik-public:
    external: true
